#!/usr/bin/env node
// Generates docs/DEPENDENCY-LICENSES.md from package-lock.json (deterministic, no network).
// Usage: node scripts/license-audit.mjs [--check]   (--check exits 1 when the committed file is stale)
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(ROOT, "docs", "DEPENDENCY-LICENSES.md");
const PERMISSIVE = new Set(["MIT", "ISC", "BSD-2-Clause", "BSD-3-Clause", "Apache-2.0", "0BSD", "Unlicense", "CC0-1.0"]);
const lock = JSON.parse(readFileSync(resolve(ROOT, "package-lock.json"), "utf8"));
const pkg = JSON.parse(readFileSync(resolve(ROOT, "package.json"), "utf8"));

const rows = Object.entries(lock.packages)
  .filter(([path]) => path !== "")
  .map(([path, p]) => ({
    name: path.replace(/^.*node_modules\//, ""),
    version: p.version ?? "?",
    license: typeof p.license === "string" ? p.license : "UNKNOWN",
    dev: p.dev === true || p.devOptional === true,
    optional: p.optional === true || p.devOptional === true
  }))
  .sort((a, b) => (a.name === b.name ? (a.version < b.version ? -1 : 1) : a.name < b.name ? -1 : 1));

const runtime = rows.filter((r) => !r.dev);
const dev = rows.filter((r) => r.dev);
const notPermissive = rows.filter((r) => !PERMISSIVE.has(r.license));
const table = (list) =>
  ["| Package | Version | License |", "| --- | --- | --- |", ...list.map((r) => `| ${r.name} | ${r.version} | ${r.license} |`)].join("\n");

const lines = [
  "# Dependency license audit",
  "",
  "Generated by `node scripts/license-audit.mjs` from `package-lock.json`. Do not edit by hand; `scripts/verify-quality.sh` fails when this file is stale.",
  "",
  `Direct runtime dependencies: ${Object.entries(pkg.dependencies ?? {}).map(([n, v]) => `${n}@${v}`).join(", ") || "none"}.`,
  `Project license: ${pkg.license}. Total locked packages: ${rows.length} (runtime ${runtime.length}, dev-only ${dev.length}).`,
  "",
  "Policy: the shipped runtime closure must be permissively licensed (MIT, ISC, BSD, Apache-2.0). Dev-only tooling is never shipped in the published package (`files` allowlist in `package.json`).",
  "",
  "## Packages outside the permissive set",
  "",
  notPermissive.length
    ? [
        "These are dev-only build/test tooling pulled in transitively (not shipped, not linked into `dist/`). Review before any change that would ship them.",
        "",
        table(notPermissive),
        "",
        `Runtime (shipped) packages outside the permissive set: ${notPermissive.filter((r) => !r.dev).length}.`
      ].join("\n")
    : "None.",
  "",
  "## Runtime closure",
  "",
  runtime.length ? table(runtime) : "No third-party runtime packages.",
  "",
  "## Dev-only closure",
  "",
  dev.length ? table(dev) : "None.",
  ""
];
const text = lines.join("\n");

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    // missing file counts as stale
  }
  if (current !== text) {
    process.stderr.write("docs/DEPENDENCY-LICENSES.md is stale: run `node scripts/license-audit.mjs`\n");
    process.exit(1);
  }
  const shippedBad = notPermissive.filter((r) => !r.dev);
  if (shippedBad.length) {
    process.stderr.write(`non-permissive runtime dependency: ${shippedBad.map((r) => r.name).join(", ")}\n`);
    process.exit(1);
  }
  process.stdout.write("license audit current\n");
} else {
  writeFileSync(OUT, text);
  process.stdout.write(`wrote ${OUT} (${rows.length} packages)\n`);
}
